theme = "hugo-theme-codex"

# Override these settings with your own
title = "Hi, I'm Jordi."
languageCode = "en-us"
baseURL = "https://jordinebot.me/"
copyright = "© {year}, Jordi Nebot"

# Add your Disqus shortname here.
# disqusShortname = ""

# Add your Google Analytics identifier: UA-XXXXXXXX-X
# googleAnalytics = ""

# Optional params
[params]
  # Follow the Hugo date/time format reference here:
  # https://gohugo.io/functions/format/#gos-layout-string
  dateFormat = "Jan 2 2006"

  # Links to your social accounts, comment/uncomment as needed. Icons will be displayed for those specified.
  email = "mailto:hola@jordinebot.cat"
  # github = "https://github.com/jordinebot"
  # instagram = "https://instagram.com/<your handle>"
  # linkedin = "https://www.linkedin.com/in/jnebot/"

  # Titles for your icons (shown as tooltips), and also their display order.
  # Currently, these icons are supported:
  #   "Twitter", "GitHub", "Email", "Facebook", "GitLab", "Instagram", "LinkedIn", "YouTube"
  iconOrder = [""]

  # Metadata for Twitter cards, defaults to params.twitter
  # twitterSite = "@<your handle>"
  # twitterAuthor = "@<your handle>"

  # Set to true to display page title in table of contents in blog posts.
  showPageTitleInTOC = false

# This disables Hugo's default syntax highlighting in favor
# of prismjs. If you wish to use Hugo's default syntax highlighting
# over prismjs, remove this. You will also need to remove the prismjs
# vendor script in layouts/blog/single.html.
[markup]
  [markup.highlight]
    codeFences = false

  # Set to false to disallow raw HTML in markdown files
  [markup.goldmark.renderer]
      unsafe = true

# Controls the navigation
[[menu.main]]
  identifier = "home"
  name = "Home"
  title = "Home"
  url = "/"
[[menu.main]]
  identifier = "about"
  name = "About"
  title = "About"
  url = "/about"
[[menu.main]]
  identifier = "blog"
  name = "Blog"
  title = "Blog"
  url = "/posts"
